# Generated by Django 4.2.8 on 2023-12-22 08:38

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image_bio', models.ImageField(upload_to=design.models.image_upload)),
                ('images', models.FileField(blank=True, default=None, max_length=3000, null=True, upload_to=design.models.image_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
