# Generated by Django 4.2.8 on 2023-12-22 08:56

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='images',
        ),
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(default=1, upload_to=design.models.image_upload),
            preserve_default=False,
        ),
    ]
