# Generated by Django 4.2.8 on 2023-12-22 10:27

import design.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_rename_image_design_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='images',
        ),
        migrations.CreateModel(
            name='DesignImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=design.models.image_upload)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.design')),
            ],
        ),
    ]
