# Generated by Django 4.2.8 on 2023-12-18 18:45

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=60, verbose_name='service_name')),
                ('service_bio', models.CharField(max_length=225, verbose_name='service_bio')),
                ('service_disc', models.CharField(max_length=420, verbose_name='service_disc')),
                ('service_logo', models.ImageField(upload_to=services.models.image_upload)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
